# Generated by Django 5.1.6 on 2025-05-18 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='job',
        ),
        migrations.RemoveField(
            model_name='category',
            name='logo_name',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
    ]
