# Generated by Django 5.1.6 on 2025-05-18 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AddField(
            model_name='username',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
