# Generated by Django 5.1.6 on 2025-05-18 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
