# Generated by Django 5.1.6 on 2025-05-18 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_alter_skill_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='text',
        ),
        migrations.AddField(
            model_name='skill',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
