# Generated by Django 5.1.6 on 2025-05-18 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_remove_skill_text_skill_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='progress',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
