# Generated by Django 5.1.6 on 2025-05-18 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_skill_progress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='description',
        ),
    ]
