# Generated by Django 5.1.6 on 2025-05-18 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='urls',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
