# Generated by Django 5.1.6 on 2025-05-18 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_work_urls'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='urls',
        ),
        migrations.AddField(
            model_name='work',
            name='link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
