# Generated by Django 4.2.16 on 2026-09-24 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0018_alter_contact_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='cv/'),
        ),
    ]
